eLearn/urls.py
"""Defines URL patterns for eLearn."""

from django.urls import path
from . import views

app_name = "eLearn"

urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    
    path('<int:course_id>/main/', views.main, name='main'),
    path('main/', views.main, name='main'),

    path('list/', views.CourseListView.as_view(), name='list_course'),
    path('create/', views.CourseCreateView.as_view(), name='create_course'),
    path('<pk>/edit/', views.CourseUpdateView.as_view(), name='edit_course'),
    path('<pk>/delete/', views.CourseDeleteView.as_view(), name='delete_course'),

    path('<int:course_id>/listvideos/', views.list_video, name='list_video'),
    path('<int:course_id>/createvideo/', views.create_video, name='create_video'),
    path('<int:video_id>/editvideo/', views.edit_video, name='edit_video'),
    path('<int:video_id>/deletevideo/', views.delete_video, name='delete_video')
]

elearning/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('eLearn.urls')),
    path('users/', include('users.urls')),
]

users/urls.py
"""Defines URL patterns for users"""

from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = "users"

urlpatterns = [
    # Login page
    path('login/',
         auth_views.LoginView.as_view(template_name='users/login.html'),
         name='login'),

    # Logout page
    path('logout/', views.logout_view, name='logout'),

    # Registration page
    path('register/', views.register, name='register'),
]

eLearn/models.py
from django.db import models
from users.models import CustomUser

class Course(models.Model):
    professor = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=150, unique=True)
    description = models.TextField()
    uploadDate = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-uploadDate']

    def __str__(self):
        return self.name


class Video(models.Model):
    course = models.ForeignKey('Course', related_name='modules', on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    videoid = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    # created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

eLearn/forms.py
from django import forms

from .models import Video

class VideoForm(forms.ModelForm):
    class Meta:
        model = Video
        fields = ['id', 'name', 'videoid','description']
        labels = {'id': 'id', 'name': 'name', 'videoid': 'videoid', 'description':'description'}

eLearn/views.py
from django.urls import reverse_lazy
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Course, Video
from .forms import VideoForm

def index(request):
    """The home page for eLearning"""
    course_list = Course.objects.all()
    course1 = course_list[0]
    course2 = course_list[1]
    video = Video.objects.filter(course= course1)
    video1 = video[0]
    video = Video.objects.filter(course= course2)
    video2 = video[0]
    context = {
        'course1': course1,
        'course2': course2,
        'video1': video1,
        'video2': video2,
    }
    return render(request, 'eLearn/index.html', context)

@login_required
def main(request, course_id=0):
    """The main page for eLearning"""
    my_courses=[]
    authenticated_user = request.user

    if authenticated_user.userType == 2:
        my_courses = Course.objects.filter(professor_id=authenticated_user)
        if len(my_courses)!=0 and course_id == 0:
            selected_course = Course.objects.filter(professor_id=authenticated_user).latest('uploadDate')
        elif len(my_courses) == 0:
            selected_course = None
        else:
            selected_course = get_object_or_404(Course, id=course_id)
        videos = selected_course.modules.order_by('id')
        context = {'courses': my_courses,
                   'selected_course': selected_course,
                   'userType': "professor",
                   'videos': videos,
                   'user': authenticated_user}
        return render(request, 'eLearn/main.html', context)
    else:
        my_courses = Course.objects.all()
        if course_id == 0:
            selected_course = my_courses.latest('uploadDate')
        else:
            selected_course = get_object_or_404(Course, id=course_id)
        videos = selected_course.modules.order_by('id')
        context = {'courses': my_courses,
                   'selected_course': selected_course,
                   'userType': "student",
                   'videos': videos,
                   'user': authenticated_user
                   }
        return render(request, 'eLearn/main.html', context)

    return render(request, 'eLearn/main.html')

class CourseListView(ListView):
    model = Course
    template_name = 'eLearn/list.html'
    context_object_name = 'courses'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        latest_course = Course.objects.latest('uploadDate')
        context['selected_course'] = latest_course
        my_courses = Course.objects.filter(professor_id=self.request.user)

        authenticated_user = self.request.user
        if authenticated_user.userType == 2:
            context['userType'] = "professor"
        else:
            context['userType'] = "student"

        context['courses'] = my_courses

        return context

class CourseCreateView(CreateView):
    model = Course
    fields = ['name', 'slug', 'description']
    success_url = reverse_lazy('eLearn:list_course')
    template_name = 'eLearn/form.html'

    def form_valid(self, form):
         professor = self.request.user
         form.instance.professor = professor
         return super(CourseCreateView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        latest_course = Course.objects.latest('uploadDate')
        context['selected_course'] = latest_course

        authenticated_user = self.request.user
        context['courses'] = Course.objects.filter(professor_id=self.request.user)
        if authenticated_user.userType == 2:
            context['userType'] = "professor"
        else:
            context['userType'] = "student"

        return context

class CourseUpdateView(UpdateView):
    model = Course
    fields = ['name', 'slug', 'description']
    success_url = reverse_lazy('eLearn:list_course')
    template_name = 'eLearn/form.html'

    def form_valid(self, form):
         professor = self.request.user
         form.instance.professor = professor
         return super(CourseUpdateView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        latest_course = Course.objects.latest('uploadDate')
        context['selected_course'] = latest_course
        context['courses'] = Course.objects.filter(professor_id=self.request.user)

        authenticated_user = self.request.user
        if authenticated_user.userType == 2:
            context['userType'] = "professor"
        else:
            context['userType'] = "student"

        return context

class CourseDeleteView(DeleteView):
    model = Course
    template_name = 'eLearn/delete.html'
    success_url = reverse_lazy('eLearn:list_course')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        latest_course = Course.objects.latest('uploadDate')
        context['selected_course'] = latest_course
        context['courses'] = Course.objects.filter(professor_id=self.request.user)

        authenticated_user = self.request.user
        if authenticated_user.userType == 2:
            context['userType'] = "professor"
        else:
            context['userType'] = "student"

        return context

def list_video(request, course_id):
    """Show a single course and it's videos."""
    courses = Course.objects.filter(professor_id = request.user)
    course = get_object_or_404(Course, id=course_id)

    latest_course = Course.objects.latest('uploadDate')

    if course.professor != request.user:
        raise Http404

    videos = course.modules.order_by('id')
    context = {'courses': courses,
               'course': course,
               'videos': videos,
               'userType': "professor",
               'selected_course': latest_course}
    return render(request, 'eLearn/videolist.html', context)

def create_video(request, course_id):
    """Create a new video for the course."""
    courses = Course.objects.filter(professor_id = request.user)
    course = get_object_or_404(Course, id=course_id)
   
    latest_course = Course.objects.latest('uploadDate')

    if course.professor != request.user:
        raise Http404

    if request.method != 'POST':
        form = VideoForm()
    else:
        form = VideoForm(data=request.POST)
        if form.is_valid():
            new_video = form.save(commit=False)
            new_video.course = course
            new_video.save()
            return HttpResponseRedirect(reverse('eLearn:list_video',
                                                args=[course_id]))

    context = {'form': form,
               'courses': courses,
               'userType': "professor",
               'selected_course': latest_course}
    return render(request, 'eLearn/create_video.html', context)

def edit_video(request, video_id):
    """Edit a single video."""
    courses = Course.objects.filter(professor_id = request.user)
    video = get_object_or_404(Video, id=video_id)
    course = video.course

    latest_course = Course.objects.latest('uploadDate')

    if course.professor != request.user:
        raise Http404

    if request.method != 'POST':
        form = VideoForm(instance=video)
    else:
        # POST data submitted; process data.
        form = VideoForm(instance=video, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('eLearn:list_video',
                                                args=[course.id]))

    context = {'form': form,
               'courses': courses,
               'userType': "professor",
               'selected_course': latest_course}
    return render(request, 'eLearn/create_video.html', context)
    

def delete_video(request, video_id):
    """Delete a single video."""
    video = get_object_or_404(Video, id=video_id)
    course = video.course

    if course.professor != request.user:
        raise Http404

    video.delete()
    return HttpResponseRedirect(reverse('eLearn:list_video',
                                        args=[course.id]))



eLearn/templates/eLearn/base.html
{% load bootstrap4 %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{{title}}</title>
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    <link rel="stylesheet" type="text/css" href="{% static 'eLearn/style.css' %}">

  </head>

  <body>
    <!-- Static navbar -->
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
      {% if user.is_authenticated %}
        <a class="navbar-brand" href="{% url 'eLearn:main' %}">eLearning</a>
      {% else %}
        <a class="navbar-brand" href="{% url 'eLearn:index' %}">eLearning</a>
      {% endif %}
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          {% if user.is_authenticated %}
            <div class="nav-item nav-link active">Hello, {{ user.username }}.</div>
            <a class="nav-item nav-link" href="{% url 'users:logout' %}">log out<span class="sr-only">(current)</span></a>
          {% else %}
            <a class="nav-item nav-link" href="{% url 'users:register' %}">register</a>
            <a class="nav-item nav-link" href="{% url 'users:login' %}">log in</a>
          {% endif %}
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="page-header mt-5">
        {% block header %}{% endblock header %}
      </div>
      <div>
{#        course bar#}
        <div class="row">
          <div class="col-2">
            {% if userType == "professor" %}
              <div class="p-2 border border-dark rounded bg-light">
                <div>
                  <h4>Edit your courses</h4>
                </div>
                <div class="nav flex-column nav-pills red" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                  <a class="nav-link active" id="v-pills-editCourse-tab" href="{% url 'eLearn:list_course' %}" role="tab" aria-controls="v-pills-editCourse" aria-selected="true">Edit Courses</a>
                </div>
              </div>
              <div class="pt-4" ></div>
            {% endif %}
            <div class="p-2 border border-dark rounded bg-light">
              <div>
                <h4>Courses</h4>
              </div>
              {% for course in courses %}
                {% if course == selected_course and selected_course != None%}
                  <div class="nav flex-column nav-pills red" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                    <a class="nav-link active" id="v-pills-editCourse-tab" href="{% url 'eLearn:main' course.id %}" role="tab" aria-controls="v-pills-editCourse" aria-selected="true">{{ course }}</a>
                  </div>
                {% else %}
                  <div class="nav flex-column nav-pills red" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                    <a class="nav-link" id="v-pills-editCourse-tab" href="{% url 'eLearn:main' course.id %}" role="tab" aria-controls="v-pills-editCourse" aria-selected="true">{{ course }}</a>
                  </div>
                {% endif %}
              {% empty %}
              {% endfor %}
            </div>
          </div>
            {% block content %}{% endblock content %}
        </div>
      </div>
    </div> <!-- /container -->

    <script>
      $(document).ready(function() {
        {% block domready %}
        {% endblock %}
      });
    </script>
  </body>
</html>

eLearn/templates/eLearn/create_video.html
{% extends "eLearn/base.html" %}
{% load bootstrap4 %}

{% block content %}

  <div class="col-8">
    <div class="tab-content" id="v-pills-tabContent">
      <h1>
        {% if object %}
          Edit course "{{ object.name }}"
        {% else %}
          Add a new video
        {% endif %}
      </h1>
      <div class="module">
        <h2>Video info</h2>
        <form action="." method="post">
          {% bootstrap_form form %}
          {% csrf_token %}
          <p><input type="submit" value="Save video" class="btn btn-primary" role="button"></p>
        </form>
      </div>
    </div>
  </div>

{% endblock %}

eLearn/templates/eLearn/delete.html
{% extends "eLearn/base.html" %}
{% load bootstrap4 %}

{% block content %}

  <div class="col-8">
    <div class="tab-content" id="v-pills-tabContent">
      <h1>Delete course "{{ object.name }}"</h1>
    
      <div class="module">
        <form action="" method="post">
          {% csrf_token %}
          <p>Are you sure you wanted to delete "{{ object }}"?</p>
          {% buttons %}
            <p><input type="submit" class="btn btn-danger" role="button" value="Confirm"></p>
          {% endbuttons %}
        </form>
      </div>
    </div>
  </div>
 
{% endblock content %}

eLearn/templates/eLearn/form.html
{"req_data": "",
 "priv_status": true,
 "banner": "*******\r\nWelcome to ZXR10 5928PS Switch of ZTE Corporation\r\n*******\r\n
    Username:", "priv_error": "", "req_name": "telnet_negotiate",
    "status_code": 0, "timestamp": ""},

{"type": "","brand": "", "type_sim": 0, "model": "",
    "category_sim": 0, "category": "", "brand_sim": 0,
    "model_sim": 0, "priv_finger_id": "", "version_sim": 0, "version": ""},
"banner_list": [{"req_data": "",
    "priv_status": true,
    "banner": "Welcome !
               ZTE Corporation.
               All rights reserved.",
    "priv_error": "", "req_name": "telnet_negotiate", "status_code": 0, "timestamp": ""}

eLearn/templates/eLearn/index.html
{% extends "eLearn/indexBase.html" %}
{% load static %}

{% block header %}
    <div class="container" aria-rowspan="50px" aria-colspan="50-x">
      <div id="carouselIndicators" class="carousel slide  carousel-fade" data-ride="carousel">
          <ol class="carousel-indicators">
            <li data-target="#carouselIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselIndicators" data-slide-to="1"></li>
            <li data-target="#carouselIndicators" data-slide-to="2"></li>
          </ol>
          <div class="carousel-inner">
            <div class="carousel-item active" >
              <img class="d-block w-100" src="{% static "media/python.jpeg" %}" alt="First slide">
            </div>
            <div class="carousel-item">
              <img class="d-block w-100" src="{% static "media/learn.jpg" %}" alt="Second slide">
            </div>
            <div class="carousel-item">
              <img class="d-block w-100" src="{% static "media/lab.jpg" %}" alt="Third slide">
            </div>
          </div>
          <a class="carousel-control-prev" href="#carouselIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
      </div>
    </div>
{% endblock header %}

{% block content %}
    <div class="row container-fluid" aria-rowspan="50px" aria-colspan="50-x" style="margin-top:50px;  margin-left: auto; margin-right: auto">
        <div class="container" style="background-color: #343a40; width:520px; box-shadow: 1px -1px 1px #444, -1px 1px 1px #444;">
            {% if user.is_authenticated %}
                <div style=""><a href="{% url 'eLearn:main' %}"><img src="https://i1.ytimg.com/vi/{{ video1.videoid }}/0.jpg" class="img-rounded"></a></div>
            {% else %}
                <div style=""><a href="{% url 'users:login' %}"><img src="https://i1.ytimg.com/vi/{{ video1.videoid }}/0.jpg" class="img-rounded"></a></div>
            {% endif %}
            <div><h3 style="color: darkgray">{{ course1.name }}</h3></div>
            <div><h5 style="color: darkgray">{{ course1.description }}</h5></div>
        </div>
        <div class="container" style="background-color: #343a40; width:520px; box-shadow: 1px -1px 1px #444, -1px 1px 1px #444;">
            {% if user.is_authenticated %}
                <div style=""><a href="{% url 'eLearn:main' %}"><img src="https://i1.ytimg.com/vi/{{ video2.videoid }}/0.jpg" class="img-rounded"></a></div>
            {% else %}
                <div style=""><a href="{% url 'users:login' %}"><img src="https://i1.ytimg.com/vi/{{ video2.videoid }}/0.jpg" class="img-rounded"></a></div>
            {% endif %}
            <div><h3 style="color: darkgray">{{ course2.name }}</h3></div>
            <div><h5 style="color: darkgray">{{ course2.description }}</h5></div>
        </div>
    </div>
{% endblock content %}

eLearn/templates/eLearn/indexBase.html
{% load bootstrap4 %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{{title}}</title>
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    <link rel="stylesheet" type="text/css" href="{% static 'eLearn/style.css' %}">

  </head>

  <body>

    <!-- Static navbar -->
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
      {% if user.is_authenticated %}
        <a class="navbar-brand" href="{% url 'eLearn:main' %}">eLearning</a>
      {% else %}
        <a class="navbar-brand" href="{% url 'eLearn:index' %}">eLearning</a>
      {% endif %}
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          {% if user.is_authenticated %}
            <div class="nav-item nav-link active">Hello, {{ user.username }}.</div>
            <a class="nav-item nav-link" href="{% url 'users:logout' %}">log out<span class="sr-only">(current)</span></a>
          {% else %}
            <a class="nav-item nav-link" href="{% url 'users:register' %}">register</a>
            <a class="nav-item nav-link" href="{% url 'users:login' %}">log in</a>
          {% endif %}
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="page-header mt-5">
        {% block header %}{% endblock header %}
      </div>
      <div>
        {% block content %}{% endblock content %}
      </div>
    </div> <!-- /container -->

    <script>
      $(document).ready(function() {
        {% block domready %}
        {% endblock %}
      });
    </script>
  </body>
</html>

eLearn/templates/eLearn/list.html
{% extends "eLearn/base.html" %}

{% block content %}

  <div class="col-8">
    <div class="tab-content" id="v-pills-tabContent">
      <h1>eLearning courses</h1>
      
      <p>
        <a href="{% url 'eLearn:create_course' %}" class="btn btn-primary" role="button">Create new course</a>
      </p>

      <div class="module">
        {% for course in courses %}
          <div class="card card-body bg-light">
            <h3>{{ course.name }}</h3>
            <p>
              <a href="{% url 'eLearn:edit_course' course.id %}" class="btn btn-primary" role="button">Edit course</a>
              <a href="{% url 'eLearn:delete_course' course.id %}" class="btn btn-warning" role="button">Delete course</a>
              <a href="{% url 'eLearn:list_video' course.id %}" class="btn btn-primary" role="button">Edit course videos</a>
            </p>
          </div>
          </br>
        {% empty %}
          <p>You haven't created any courses yet.</p>
        {% endfor %}
        <p>
          <a href="{% url 'eLearn:create_course' %}" class="btn btn-primary" role="button">Create new course</a>
        </p>
      </div>
    </div>
  </div>

  <div class="col-2">
  </div>

{% endblock %}

eLearn/templates/eLearn/main.html
{% extends "eLearn/base.html" %}

{% block content %}

  <div class="col-8">
{#    video playback; formation of url: https://www.youtube.com/embed/{{ video.vid }}#}
    <div class="tab-content" id="v-pills-tabContent">
      {% for video in videos %}
        {% if forloop.first %}
          <div class="tab-pane fade show active" id="v-pills-{{ video.id }}" role="tabpanel" aria-labelledby="v-pills-home-tab">
            <div class="embed-responsive embed-responsive-16by9">
              <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/{{ video.videoid }}" allowfullscreen></iframe>
            </div>
          </div>
        {% else %}
          <div class="tab-pane fade" id="v-pills-{{ video.id }}" role="tabpanel" aria-labelledby="v-pills-home-tab">
            <div class="embed-responsive embed-responsive-16by9">
              <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/{{ video.videoid }}" allowfullscreen></iframe>
            </div>
          </div>
        {% endif %}
      {% endfor %}
    </div>
  </div>
  <div class="col-2">
{#    video list#}
    <div class="p-2 border border-dark rounded bg-light">
      <div class="nav flex-column nav-pills red" id="v-pills-tab" role="tablist" aria-orientation="vertical">
          <h4>{{ selected_course }}</h4>
        {% for video in videos %}
          {% if forloop.first %}
          <a class="nav-link active" id="v-pills-{{ video.id }}-tab" data-toggle="pill" href="#v-pills-{{ video.id }}" role="tab" aria-controls="v-pills-{{ video.id }}" aria-selected="true">{{ video.name }}</a>
          {% else %}
          <a class="nav-link" id="v-pills-{{ video.id }}-tab" data-toggle="pill" href="#v-pills-{{ video.id }}" role="tab" aria-controls="v-pills-{{ video.id }}" aria-selected="false">{{ video.name }}</a>
          {% endif %}
        {% endfor %}
      </div>
    </div>
  </div>

{% endblock content %}

eLearn/templates/eLearn/videolist.html
{% extends "eLearn/base.html" %}

{% block content %}

  <div class="col-8">
    <div class="tab-content" id="v-pills-tabContent">
      <h1>{{ course }}</h1>
    
      <p>
        <a href="{% url 'eLearn:create_video' course.id %}" class="btn btn-primary" role="button">Add a video</a>
      </p>

      <div class="module">
        {% for video in videos %}
          <div class="card card-body bg-light">
            <h3>{{ video.name }}</h3>
            <p>
              <a href="{% url 'eLearn:edit_video' video.id %}" class="btn btn-primary" role="button">Edit</a>
              <a href="{% url 'eLearn:delete_video' video.id %}" class="btn btn-primary" role="button">Delete</a>
            </p>
          </div>
          </br>
        {% empty %}
          <p>You haven't added any videos yet.</p>
        {% endfor %}
        <p>
          <a href="{% url 'eLearn:create_video' course.id %}" class="btn btn-primary" role="button">Add a video</a>
        </p>
      </div>
    </div>
  </div>

  <div class="col-2">
  </div>

{% endblock %}